name: Staging Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Start Sync
      env:
        DEST_DIR: 'www/mcd-repo/laravel-ics'
        DEPLOY_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        eval `ssh-agent`
        ssh-add - <<< "${DEPLOY_KEY}"
        ssh -tt -vvv u668-zznpt3duudzt@mycardirect.co.uk -p 18765 -o StrictHostKeyChecking=no
        cd www/mcd-repo/laravel-ics
