name: Staging Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Start Sync
      env:
        DEST_DIR: 'www/mcd-repo/laravel-ics'
      run: |
        echo "${{secrets.SECRET_KEY}}" > deploy_key
        chmod 600 deploy_key
        ssh -tt -vvv -i deploy_key u668-zznpt3duudzt@mycardirect.co.uk -p 18765 -o StrictHostKeyChecking=no
        cd www/mcd-repo/laravel-ics
